spring.application.name=SpringAiDemo

spring.ai.openai.api-key=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
